name: Build, Push to DockerHub, and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  # -----------------------------------------------
  # JOB 1: Build and Push the image to DockerHub
  # -----------------------------------------------
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKORHUB_USERNAME }}/hello-world-aws:latest

  # -----------------------------------------------
  # JOB 2: Deploy the new image to the EC2 server
  # -----------------------------------------------
  deploy-to-ec2:
    # This job 'needs' (waits for) 'build-and-push' to finish
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 instance
        # This action logs into your server using your secrets
        uses: appleboy/ssh-action@v1.0.3
        with:
          # The 3 EC2 secrets you just added
          host: ${{ secrets.EC2_HOST_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}

          # The script to run INSIDE your EC2 server
          script: |
            # 1. Pull the new image from DockerHub
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/hello-world-aws:latest

            # 2. Check if a container named 'hello-world-app' is already running
            if [ "$(sudo docker ps -q -f name=hello-world-app)" ]; then
                # 3. If it exists, stop and remove it
                sudo docker stop hello-world-app
                sudo docker rm hello-world-app
            fi

            # 4. Run the new container with the fresh image
            # We give it a name ('--name') so we can find it next time
            sudo docker run -d --name hello-world-app -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/hello-world-aws:latest
